### ISSUE TITLE
Suggestion: Filter should indicate invalid command when no valid predicates are detected

### ISSUE THREAD

**Issue by ranaldmiao** [CS2103-AY1819S1-W17-4/main#180] opened 2018-10-28 17:49 UTC
Just a suggestion:
When no valid predicates are detected, Filter command should indicate so to the user.

Example:
![image](https://user-images.githubusercontent.com/2166767/47619642-2f10d680-db1c-11e8-929c-0c0fae7c8afd.png)

Expected Response:
![image](https://user-images.githubusercontent.com/2166767/47619645-3d5ef280-db1c-11e8-8463-25ced5719e90.png)

**Comment by btzy** [comment] 2018-10-28 23:36
This is due to issue #175, and should be fixed in PR #176.

**Comment by btzy** [comment] 2018-10-29 07:07
Limited to alphanumeric characters and `_`, `-`, `/` by #176.  The rest of the issue is not a bug.

**Closed by btzy** 2018-10-29 07:07 UTC
Labels: severity.Low
